name: publish executable file to release page
on:
  push:
    tags:
    - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyInstaller and dependencies
        run: |
          python -m pip install --upgrade -r requirements.txt pip PyInstaller

      - name: set version
        run: |
          Write-Output ("VERSION=" + ("${{ github.ref_name }}" -replace 'v', '')) >> "$env:GITHUB_ENV"

      - name: Create executable file with pyinstaller and zip
        run: |
          pyinstaller ${{ github.event.repository.name }}.py `
            "--onefile" `
            "--noconsole" `
            "--icon=Assets/sample.ico" `
            "--exclude-module=PIL._avif" `
            "--exclude-module=PIL._imagingcms" `
            "--add-data=Assets/version.txt;Assets"
          pushd dist
          Compress-Archive -Path "${{ github.event.repository.name }}.exe" -DestinationPath "${{ github.event.repository.name }}-${{ env.VERSION }}.zip"
          popd

      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ github.event.repository.name }}-${{ env.VERSION }}.zip
